### ISSUE TITLE
10.18

### ISSUE THREAD

**Issue by ariescc** [ariescc/LibrarySystemProject#31]
1、用户密码错误，跳转页面更改
2、保存绑定信息的时候，让其调到主页
3、普通用户不能有borrow book，将borrow改为copy
4、pagebar有问题
5、内容编辑edit有问题
6、管理员添加图书 不是borrow book
7、图书管理不展示price
8、借书页面的edit删除
9、还书的时候如果没找到这本书，产生404
10、用户管理放到admin

**Comment by ygjch** [comment]
个人信息中邮箱和电话更改未保存
